import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 仅保留 Anvil 文档分组
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Anvil 源码导读',
      link: {
        type: 'generated-index',
        title: 'Anvil 源码导读',
        description: '基于 crates/anvil 源码的结构化解析（中文站，后续考虑英文翻译）',
      },
      items: [{ type: 'autogenerated', dirName: 'anvil' }],
    },
  ],
};

export default sidebars;
