import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 手动组织侧边，保留原有教程示例并新增 Anvil Walkthrough 分组
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    },
    {
      type: 'category',
      label: 'Anvil Walkthrough',
      // 目录入口文档
      link: { type: 'doc', id: 'anvil/introduction' },
      // 从 docs/anvil 目录自动生成其余层级
      items: [{ type: 'autogenerated', dirName: 'anvil' }],
    },
  ],
};

export default sidebars;
